### ISSUE TITLE
metadata lookup/cleanup

### ISSUE THREAD

**Issue by revgum** [osulp/dspace2hydra#1]
- [x] issue #2 identify files which should not be loaded into hydra 
- [x] issue #3 identify metadata that should not be loaded into hydra
- [x] issue #4 find and associate URIs for linked data metadata

**Comment by revgum** [comment]
This work is largely done, and the method for adding more metadata fields is well established.
